server:
  port: 8083
spring:
  config:
    import: configserver:http://localhost:8888
    
#  datasource:
#    password: postgre
#    url: jdbc:postgresql://localhost/olxadvertise
#    username: postgres
#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true

# Content Negotiation
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: advertise-service 
  zipkin:
    base-url: http://localhost:9411
# For circuit breaker  
management:
  endpoints:
   web:
     exposure:
       include: "*"
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
     show-details: always
     
resilience4j:
  circuitbreaker:
    instances:
      VALIDATE-CIRCUIT-BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        
      GET-ALL-CATEGORY-CIRCUIT-BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        
      GET-CATEGORY-BY-ID-CIRCUIT-BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        
      GET-ADVERTISE-STATUS-CIRCUIT-BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        
      GET-USERNAME-CIRCUIT-BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true